//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uadeegonline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_category
    {
        public int cat_id { get; set; }
        public string cat_name { get; set; }
        public string cat_desc { get; set; }
    }
}
